library(randomForest)
library(tidyverse)
data = read.csv('train.csv')
test_data = read.csv('test.csv')
titanic_data = data %>% select(Pclass,Sex,Age,SibSp,Parch,Fare,Survived)
test_data = test_data %>% select(PassengerId,Pclass,Sex,Age,SibSp,Parch,Fare)
titanic_data$Sex = factor(titanic_data$Sex, levels = c('male','female'), labels = c(1,2))
titanic_data$Age = ifelse(test = is.na(titanic_data$Age), yes = ave(titanic_data$Age, FUN = function(x) mean(x ,na.rm = TRUE)), no = titanic_data$Age)
titanic_data$Fare = ifelse(test = is.na(titanic_data$Fare), yes = ave(titanic_data$Fare, FUN = function(x) mean(x ,na.rm = TRUE)), no = titanic_data$Fare)
titanic_data$Survived = factor(titanic_data$Survived)
test_data$Fare = ifelse(test = is.na(test_data$Fare), yes = ave(test_data$Fare, FUN = function(x) mean(x ,na.rm = TRUE)), no = test_data$Fare)
test_data$Sex = factor(test_data$Sex, levels = c('male','female'), labels = c(1,2))
test_data$Age = ifelse(test = is.na(test_data$Age), yes = ave(test_data$Age, FUN = function(x) mean(x ,na.rm = TRUE)), no = test_data$Age)
#regressor = lm(Survived ~ ., data = titanic_data)
classifier = randomForest(x = titanic_data[-7], y = titanic_data$Survived, ntree = 100)
y_pred = predict(classifier, newdata = test_data, type = 'class')
final = data.frame(y_pred)
#final$y_pred = ifelse(final$y_pred < 0.5, 0, 1)
result = data.frame(test_data$PassengerId,final$y_pred)
names(result) <- c('PassengerId','Survived')
write.csv(result,"S:\\Learning\\ML\\Kaggle\\titanic\\titanic_predictions_Random_Forest_classification_100.csv",row.names = FALSE)

